<div class="content-wrapper">
    <div class="units-row">
        <div class="unit unit-50 animated admin-content-box" data-animation="bounceInRight">
            <a href="<?php echo $this->url(array(), 'news-add'); ?>"><i class="fa fa-plus float-left" data-tools="tooltip" data-theme="green" title="<?php echo $this->translate('Add new news'); ?>"></i></a>
            <?php echo $this->paginationControl($this->news,
                                                'Sliding',
                                                'management/pagination.phtml'); 
            ?>
            <div class="clear"></div>
            <table class="table-stripped">
                <tr>
                    <th></th>
                    <th><?php echo $this->translate('Name'); ?></th>
                    <th><?php echo $this->translate('E-mail'); ?></th>
                    <th class="center"><?php echo $this->translate('Action'); ?></th>
                </tr>
                <?php $i = $this->news->getTotalItemCount(); ?>
                <?php if(count($this->news->getTotalItemCount())): ?>
                    <?php foreach ($this->news as $post): ?>
                        <tr>
                            <td><?php echo $i; ?></td>
                            <td><?php echo $post->name; ?></td>
                            <td><?php echo $post->email; ?></td>
                            <td class="center">
                                <a href="<?php echo $this->url(array('id' => $post->id), 'news-edit'); ?>"><i class="fa fa-pencil" data-tools="tooltip" data-theme="green" title="<?php echo $this->translate('Edit'); ?>"></i></a>
                                <a class="show-modal" data-url="<?php echo $this->url(array('id' => $post->id), 'news-delete'); ?>" data-tools="modal" data-width="300" data-title="<?php echo $this->translate('Alert'); ?>" data-content="#agreeBox" href="#"><i class="fa fa-times" data-tools="tooltip" data-theme="red" title="<?php echo $this->translate('Delete'); ?>"></i></a>
                            </td>
                        </tr>
                    <?php --$i; ?>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="4"><?php echo $this->translate('No items to display'); ?></td>
                    </tr>
                <?php endif; ?>
            </table>
            <?php echo $this->paginationControl($this->news,
                                                'Sliding',
                                                'management/pagination.phtml'); 
            ?>
            <div class="clear"></div>  
        </div>
    </div>
</div>
<div id="agreeBox" class="hidden-elem">
    <?php echo $this->translate('Are you sure?'); ?>
</div>