<?php if ($this->pageCount): ?>
<div class="paginationControl float-right">
    <ul class="pagination">
        <?php if (isset($this->previous)): ?>
        <li>
            <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
                <i class="fa fa-arrow-left"></i>
            </a>
        </li>
        <?php endif; ?>

        <?php foreach ($this->pagesInRange as $page): ?>
          <?php if ($page != $this->current): ?>
            <li>
                <a href="<?php echo $this->url(array('page' => $page)); ?>">
                    <?php echo $page; ?>
                </a>
            </li>
          <?php else: ?>
            <li><span><?php echo $page; ?></span></li>
          <?php endif; ?>
        <?php endforeach; ?>

        <?php if (isset($this->next)): ?>
        <li>
            <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
                <i class="fa fa-arrow-right"></i>
            </a>
        </li>
        <?php endif; ?>
    </ul>
</div>
<?php endif; ?>


    
    
    