<!DOCTYPE html>
<html>
    <head>
        <title>Helix Panel</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <link href="/panel/css/kube.css" media="screen" rel="stylesheet" type="text/css" >
        <link href="/panel/css/styles.css" media="screen" rel="stylesheet" type="text/css" >
        <link href="/panel/css/animate.css" media="screen" rel="stylesheet" type="text/css" >
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
        <link href='http://fonts.googleapis.com/css?family=Roboto:400,300&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <?php echo $this->layout()->content; ?>
    </body>
    <script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>
    <script src="/panel/js/main.js" type="text/javascript"></script>
</html>